### ISSUE TITLE
Nested JSON?

### ISSUE THREAD

**Issue by oneezy** [benborgers/opensheet#15]
Does this support nested JSON objects also? If so, are there any examples of that?

**Comment by benborgers** [comment]
Sorry, I’m not sure what you mean — nested JSON in the request, or in the response? Where would nested JSON be used?

**Comment by oneezy** [comment]
I was curious if the Google Sheet could be written in such a way that it could return a nested json `response` i.e. something like this...

```
{
  "name": "Oneezy",
  "url": "https://oneezy.com",
  "author": {
    "name": "Justin O'Neill",
    "email": "hello@oneezy.com",
    "url": "https://oneezy.com",
    "avatar": "https://avatars0.githubusercontent.com/u/1409898?s=460&v=4"
  },
  "social": {
    "facebook": "https://www.facebook.com/oneeeezy/",
    "twitter": "https://twitter.com/oneeezy",
    "instagram": "https://www.instagram.com/oneeeezy/",
    "linkedin": "https://www.linkedin.com/in/oneezy/",
    "github": "https://github.com/oneezy"
  }
}
```

**Comment by benborgers** [comment]
Ahh unfortunately there’s no way to get that kind of response. The values in the API response are all either strings or integers.
