### ISSUE TITLE
Support other languages.

### ISSUE THREAD

**Issue by dagemdworku** [benborgers/opensheet#16]
I used to use opensheet for my translations tasks and it used to work fine, but after four months, support for the language is not working. 

```
eg. the actual data >> "አማርኛ"
    the json data am getting >> "áŠ áˆ›áˆ­áŠ›"
```
      
If it has anything to do with the UTF-16 charset you used to support, please take a look at it.

**Comment by benborgers** [comment]
Hmm I’m seeing it come through correctly in this example: https://opensheet.elk.sh/1o5t26He2DzTweYeleXOGiDjlU4Jkx896f95VUHVgS8U/Test+Sheet

![2022-04-14 at 20 53@2x](https://user-images.githubusercontent.com/30215449/163500889-abec8c50-c881-4c0c-8c8b-0fb6b3f374a6.png)

Am I doing something different?

**Comment by dagemdworku** [comment]
After seeing this I run the api using `curl` and it works fine, it turned out safari was messing up with the response.

Thank you @benborgers for the quick response. Your api helped me a great deal on my projects.

P.S. Please let me know if there is anything I can help with, I dabble with flutter.
