### ISSUE TITLE
Open Source Request

### ISSUE THREAD

**Issue by MarketingPip** [benborgers/opensheet#17]
Hello @benborgers,

Awesome work - not just including this project! Was creeping through your other repositories as well! 

I stumbled upon this as I needed it for an upcoming project instead of other solutions. (such as converting the text file manually to JSON key in client)

I was curious if you would be willing to open source / license this project as open source. So there is no confusion about the uses for hosting this & possibility get more involvement in contributors to fix some errors such as range value errors etc. 

Thank you in advanced & thank you for hosting this freely!

**Comment by benborgers** [comment]
Yeah definitely! Do you mean by including a license file in the repository?

**Comment by MarketingPip** [comment]
@benborgers correct! 

Right now almost all your work does not have license's attached - which is fine. 
But keep in mind if you are looking to Open Source your work - assuming you are.

 `If a repository has no license, then all rights are reserved and it is not Open Source or Free. You cannot modify or redistribute this code without explicit permission from the copyright holder.`

<br>


Meaning - no commercial business can host this software LEGALLY as you own all rights to it by not including licenses dictating what they can and can't do with it

So other's know what the copyright stance is / the way your work can be legally.  Assuming you are familiar with the process.

Debating on the license you choose - would define those rights to your work. 

MIT License for example - would wave all rights to the work and let anybody & anyone do as they please with the work.

**Comment by benborgers** [comment]
I’ve added an MIT license! That’s what I intended originally, so thank you for pointing out that it wasn’t actually licensed.
