### ISSUE TITLE
Bug: Unable to parse range

### ISSUE THREAD

**Issue by MarketingPip** [benborgers/opensheet#18]
Facing issues when grabbing data when using other sheet's besides the test sheet.

`Unable to parse range.`

**Comment by benborgers** [comment]
Strange! Could you paste a URL where you're getting this error?

**Comment by MarketingPip** [comment]
More than happy too! Thank you too for the fast reply - maybe too if lucky I can pick your brain with something non related to this repo. (if willing obviously - let me know & I will add you to separate repo to ask ie; JS help related) 

[Spreadsheet to try](https://docs.google.com/spreadsheets/d/1GpUteMOS41K7c3pj7b77xF4F-7PTKZyfPK4FVQr8SVc/edit)

**Comment by benborgers** [comment]
Sure! Wanna send me an email about the other thing? benborgers@hey.com

It looks like the spreadsheet isn't shared -- could you by chance open up link sharing?

**Comment by MarketingPip** [comment]
You are the best! Thank you! You can expect a email NOW! 

Here is the updated spreadsheet [link](https://docs.google.com/spreadsheets/d/1GpUteMOS41K7c3pj7b77xF4F-7PTKZyfPK4FVQr8SVc/edit?usp=sharing) (was public before - don't know what happened lol)

& to make your life easier here is the opensheet [URL](https://opensheet.elk.sh/1GpUteMOS41K7c3pj7b77xF4F-7PTKZyfPK4FVQr8SVc/Entry+Form) with error.

**Comment by benborgers** [comment]
Ah! The last part of the URL should be the name of the tab, which in your case is “Form Responses 1”. Here’s the correct URL to use: https://opensheet.elk.sh/1GpUteMOS41K7c3pj7b77xF4F-7PTKZyfPK4FVQr8SVc/Form+Responses+1

Sorry about that! The error message is a bit cryptic.

**Comment by MarketingPip** [comment]
Thank you! I'd add this to documentation obviously for other users (assuming you're on it already😉)

And no sorry needed at all! Thank you again!
