### ISSUE TITLE
A way to set custom Title row

### ISSUE THREAD

**Issue by ScrexyScroo** [benborgers/opensheet#19]
Is there a way that this API would let use use a custom row instead relying on the first row in the sheet?

For example this sheet has the first row which isn't the title row.
https://docs.google.com/spreadsheets/d/1emW2Zsb0gEtEHiub_YHpazvBd4lL4saxCwyPhbtxXYM
https://opensheet.elk.sh/1emW2Zsb0gEtEHiub_YHpazvBd4lL4saxCwyPhbtxXYM/TV

I know that the documentation mentions that the first row should be the title row, 
but is there a way to define the title row instead?

**Comment by ScrexyScroo** [comment]
I found a way to make a live copy of google sheets using:
`=IMPORTRANGE(<googleSheetURL>,<rangeOfCells>)`

So for now I have made a copy of that doc, and selected the Titles correctly so the range would be "B2:H"
and used that with this API which solves the issue.

**Comment by benborgers** [comment]
Ah! That's a really good solution. Thank you for adding it here!
