### ISSUE TITLE
Support XML output

### ISSUE THREAD

**Issue by sntran** [benborgers/opensheet#2]
I would like to request a new output format as XML.

The endpoint would be something like this:

- `/:id/:sheet.json` to get the data as JSON, which is the default.
- `/:id/:sheet.xml` to get the data as XML.

The XML would have simple schema, a root node, and each row is a node with the same name as the sheet's.

Please let me know if that's something you would consider. Thanks!

**Comment by benborgers** [comment]
I haven’t needed to deal with XML before — what’s the usecase?

**Comment by sntran** [comment]
We have services that consume XML instead of JSON.

**Comment by benborgers** [comment]
Would it be possible to pipe the output through a package that does JSON → XML conversion?

**Comment by sntran** [comment]
Yeah, we could, but we could also just write the whole pipeline from Google Spreadsheets to XML. Your service already has the facility to support XML, so I figured it would be nice to add that into.

I can open a PR if you want.

**Comment by benborgers** [comment]
Sure! A PR would be awesome.
