### ISSUE TITLE
Call private googlesheets?

### ISSUE THREAD

**Issue by CristianHCol** [benborgers/opensheet#23]
Any way to retrieve infirmation of a private google sheet?

**Comment by benborgers** [comment]
Not at the moment, unfortunately. What’s the use-case you have in mind?

**Comment by CristianHCol** [comment]
Some customers needs to pull some data from sheets but sheets couldn't  be public, due to the information is private. So we are using this library but only could retrieve information for public sheets.

**Comment by benborgers** [comment]
That makes sense! I’ve built one-off solutions in the past that include that functionality, and am happy to discuss, but unfortunately this open source project currently doesn’t have that functionality. Sorry!
