### ISSUE TITLE
How to get data 

### ISSUE THREAD

**Issue by hieunotes** [benborgers/opensheet#24]
How to get the data from the bottom to show the results at the top???

**Comment by benborgers** [comment]
Hi! Would you be able to share a Google Sheet that you’re trying to get data from?

**Comment by hieunotes** [comment]
https://opensheet.elk.sh/1u-2O6yMLwxTBHGtqCCQJdyhjCJCUnbsdFJHZ8kGRdHc/Web!A1:Z1000

**Comment by benborgers** [comment]
Could you clarify on what the problem is? I see the two rows showing up on the opensheet API.

**Comment by hieunotes** [comment]
How to invert data from bottom up?

**Comment by benborgers** [comment]
Sorry, what do you mean by inverting data?

**Comment by hieunotes** [comment]
![Screenshot_2023-06-15-07-18-11-767_io spck](https://github.com/benborgers/opensheet/assets/34933696/6c220b3b-5d71-4c84-b051-66792186d799)

 When new data is added it At the bottom of the sheet. Not at the top

**Comment by benborgers** [comment]
Ah, you can reverse the data from the API in your app’s code. In JavaScript you would use the `reverse()` method to reverse the order.

**Comment by hieunotes** [comment]
Please give me an example

**Comment by benborgers** [comment]
Could you share the code you’re using to interact with opensheet, and the language you’re using to build your app?

**Comment by hieunotes** [comment]
Alright. Thank you very much

**Comment by hieunotes** [comment]
> 

Is there a way to get the data by column and row?

**Comment by benborgers** [comment]
Unfortunately not really, this API assumes a header column and names properties based on that header.
