### ISSUE TITLE
✨ Nested JSON ✨ (Working Demo!)

### ISSUE THREAD

**Issue by oneezy** [benborgers/opensheet#26]
yo @benborgers 

not sure if you're interested or not, but referencing #15, _1.5 years later..._ I did it! 

(let me know if you want me to submit a PR, if not all good)

# Nested JSON 
This new feature let's you create `nested.json.using.dot.notation` in the header. The flat json still works as well. 

**fork:** https://github.com/oneezy/opensheet

## Nested Demo ✨
**sheet:** https://docs.google.com/spreadsheets/d/1hFt4kkXoAx-LFZvfhsN8JITb5zuAufqhkvs0ZKTjxac/edit#gid=1657425871
**json:** https://opensheet.justinoneill2007.workers.dev/1hFt4kkXoAx-LFZvfhsN8JITb5zuAufqhkvs0ZKTjxac/nested

## Flat Demo (backwards compatible)
**sheet:** https://docs.google.com/spreadsheets/d/1hFt4kkXoAx-LFZvfhsN8JITb5zuAufqhkvs0ZKTjxac/edit#gid=0
**json:** https://opensheet.justinoneill2007.workers.dev/1hFt4kkXoAx-LFZvfhsN8JITb5zuAufqhkvs0ZKTjxac/flat

![image](https://github.com/benborgers/opensheet/assets/7369575/7543e051-e43d-4b14-94df-52257b09e64e)

**Comment by benborgers** [comment]
Ahh this makes so much sense seeing it built out!

I think unfortunately I haven’t seen a lot of demand for this, so I’m hesitant to add it to the core instance. (It would also technically be a breaking change I believe.) 

I’m glad you forked and hosted your own version though! Having that fork separate might be the best path forward.

**Comment by oneezy** [comment]
> Ahh this makes so much sense seeing it built out!
> 
> I think unfortunately I haven’t seen a lot of demand for this, so I’m hesitant to add it to the core instance. (It would also technically be a breaking change I believe.)
> 
> I’m glad you forked and hosted your own version though! Having that fork separate might be the best path forward.

It's actually backwards compatible so i think it'd just be a be feature bump

## Flat Demo 
**sheet:** https://docs.google.com/spreadsheets/d/1hFt4kkXoAx-LFZvfhsN8JITb5zuAufqhkvs0ZKTjxac/edit#gid=0
**json:** https://opensheet.justinoneill2007.workers.dev/1hFt4kkXoAx-LFZvfhsN8JITb5zuAufqhkvs0ZKTjxac/flat

**Comment by benborgers** [comment]
I _think_ it'd technically be a breaking change for columns with a dot in them already. But yeah, mostly I'm trying to keep the core project as simple as possible — it gets a _lot_ of traffic so I'm hesitant to complicate it too much.

**Comment by oneezy** [comment]
Ooo duh! I totally didn't think of that 😂

Makes sense
