### ISSUE TITLE
Trying to open sheet with slash in the tab name

### ISSUE THREAD

**Issue by tomdevlive** [benborgers/opensheet#28]
I have a sheet named 11/09 - and I'm not able to open it because the slash kinda breaks eh url. I tried to use a url enoder so it would be - 11%2F09 but that didint hekp either. I know I can do sheet order number but I dont know that. I do know the sheet ID number, like the one for the actual 11/09 sheet. could I use that somehow?

**Comment by tomdevlive** [comment]
Actually if I do try the sheet order numbe it still breaks because its trying to resolve the sheet with the slash in it.

**Comment by tiagorangel2011** [comment]
I think pr https://github.com/benborgers/opensheet/pull/30 should solve it

**Comment by tiagorangel2011** [comment]
@tomdevlive note: you still need to URL encode it
