### ISSUE TITLE
How to create arrays?

### ISSUE THREAD

**Issue by Pilag6** [benborgers/opensheet#29]
For example. If I want to have many images in one "key", how can I do it in the Google Sheet?

images: ["image1.jpg", "image2_.jpg","image3_.jpg", "image4_.jpg"]

**Comment by benborgers** [comment]
Hi - what's the format of your sheet? Do you have a URL that you can share?

**Comment by Pilag6** [comment]
https://opensheet.elk.sh/14zGBELpJ1_uUSRAjKmLoYDpkMGySKLpiIQSW4XeGkH8/1

I would like to have more than 1 image:

![image](https://github.com/benborgers/opensheet/assets/79191808/63614af7-f244-46c5-90f8-f89c8905ed11)

**Comment by benborgers** [comment]
Ah I understand, but I'm not sure that's possible in Google Sheets itself?

**Comment by tiagorangel2011** [comment]
@Pilag6 You can just use [image1, image2, image3] and then JSON.parse it.
