### ISSUE TITLE
Would it support multiple ranges?

### ISSUE THREAD

**Issue by Rplus** [benborgers/opensheet#4]
In Google Sheet API,
there is a `/values:batchGet` method to get multi range data
https://developers.google.com/sheets/api/samples/reading#read_multiple_ranges

**Comment by benborgers** [comment]
Hi! Sorry for not responding for so long. 

Unfortunately I'm not sure whether it's worth the added complexity to the API. You're definitely welcome to fork the code and expand it for your own uses though!
