### ISSUE TITLE
host not working

### ISSUE THREAD

**Issue by Alexandrsv** [benborgers/opensheet#9]
https://opensheet.elk.sh/1o5t26He2DzTweYeleXOGiDjlU4Jkx896f95VUHVgS8U/Test+Sheet

![image](https://user-images.githubusercontent.com/15097064/149488741-32922b0f-05aa-43a3-a0cf-dfef0e25f28a.png)

**Comment by benborgers** [comment]
Should be fixed! I’m really sorry, I’m going to migrate the infrastructure so this doesn’t happen again.

**Comment by Alexandrsv** [comment]
Thanks
